#!/bin/bash

# Give permission for everything in the express-app directory
sudo chmod -R 777 /home/ec2-user/express-app


# Navigate into our working directory where we have all our files
cd /home/ec2-user/express-app/server
 

# Install Node.js modules using npm
npm install


# Start your Node.js server using "npm start server.js"
pm2 start server.js


cd /home/ec2-user/express-app/client


# Start your Node.js server using "npm start server.js"
pm2 start npm -- start 

