#!/bin/bash

# Give permission for everything in the express-app directory
sudo chmod -R 777 /home/ec2-user/express-app


# Navigate into our working directory where we have all our files
cd var/www/html/server
 
# Add npm and node to path using NVM (Node Version Manager) 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Loads nvm bash_completion (Node is in the path now)

# Install Node.js modules using npm
nvm use 16
npm install


# Start your Node.js server using "npm start server.js"
pm2 start server.js > test.log

sudo service nginx restart
