#!/bin/bash

#download node and npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 16
sudo npm install pm2 -g

#Stopping existing node server
echo "Stopping any existing node servers"
pm2 kill
